/**
 * Auto-generated types from tool definitions
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * Generated by: nitrostack generate-types
 * Generated at: 2026-07-25T16:21:54.760Z
 */

// ==========================================
// Common Types
// ==========================================

export interface ToolInput<T = unknown> {
  [key: string]: T;
}

export interface ToolOutput<T = unknown> {
  [key: string]: T;
}

// ==========================================
// Tool-specific Types
// ==========================================

// query_erp
export type QueryErpInput = {
  query: string;
};
export type QueryErpOutput = unknown;

// plan_erp_query
export type PlanErpQueryInput = {
  query: string;
};
export type PlanErpQueryOutput = unknown;

// ==========================================
// Tool Name Union
// ==========================================

export type ToolName = 'query_erp' | 'plan_erp_query';

// ==========================================
// Mapped Types
// ==========================================

export interface ToolInputs {
  'query_erp': QueryErpInput;
  'plan_erp_query': PlanErpQueryInput;
}

export interface ToolOutputs {
  'query_erp': QueryErpOutput;
  'plan_erp_query': PlanErpQueryOutput;
}
